version: '3'
services:
  mikrotik-chr:
    image: gvsdhub/chr-routeros:6.49.8
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "12222:22"
      - "12223:23"
      - "18728:8728"
      - "18729:8729"
